from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, Literal, Dict, Any, List
from uuid import UUID

# --- SIGNAL & RISK LAYER EVENTS ---

class SignalCreated(BaseModel):
    """Event generated by the Strategy Agent, possessing no execution authority."""
    event_id: UUID
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    ticker: str
    suggested_action: Literal["BUY", "SELL", "HOLD"]
    suggested_horizon: str
    strategy_alias: str
    confidence: float = Field(ge=0.0, le=1.0)
    rationale: str

class RiskMetrics(BaseModel):
    account_exposure_pct: float
    volatility_atr: float
    hard_stop_loss: float

class RiskApproved(BaseModel):
    """The absolute authority event. Only exactly these payloads are processed by Execution."""
    event_id: UUID
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    signal_id: UUID
    ticker: str
    action: Literal["BUY_TO_OPEN", "SELL_TO_CLOSE", "SELL_TO_OPEN", "BUY_TO_CLOSE"]
    approved_quantity: int = Field(gt=0)
    approved_limit_price: float
    risk_metrics: RiskMetrics

class RiskRejected(BaseModel):
    """Emitted when deterministic boundaries are breached."""
    signal_id: UUID
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    reason: str
    failing_metric: str

# --- EXECUTION & BROKER ABSTRACTIONS ---

class OrderRequest(BaseModel):
    """The structured internal payload sent to the BrokerAPI Adapter."""
    internal_order_id: UUID
    idempotency_key: UUID
    ticker: str
    action: Literal["BUY", "SELL"]
    order_type: Literal["LIMIT", "MARKET", "STOP"]
    time_in_force: Literal["GTC", "DAY", "IOC", "FOK"]
    quantity: int
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    extended_hours: bool = False

class OrderResponseStatus(BaseModel):
    """Synchronous status returned directly by the Broker API post method calling."""
    broker_order_id: str
    internal_order_id: UUID
    status: Literal["ACCEPTED", "REJECTED_BY_BROKER", "RATE_LIMITED"]
    submitted_at: datetime
    raw_broker_response: Optional[Dict[str, Any]] = None

class FillEvent(BaseModel):
    """Webhook or API polled execution data indicating shares changing hands."""
    event_id: UUID
    timestamp: datetime
    internal_order_id: UUID
    broker_order_id: str
    ticker: str
    fill_price: float
    filled_quantity: int
    fees_incurred: float = 0.0
    status: Literal["PARTIALLY_FILLED", "FILLED"]

# --- AUDIT & GOVERNANCE ---

class AuditEvent(BaseModel):
    """Immutable log of any critical action."""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    correlation_id: UUID
    component: str
    input_hash: str
    decision: str
    risk_checks_passed: bool
    references: List[str]
